import { pgTable, uuid, text, numeric, integer, boolean, jsonb, timestamp, bigint } from 'drizzle-orm/pg-core';
import { categories } from './categories';

export const products = pgTable('products', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  code: text('code').unique(),
  categoryId: uuid('category_id').references(() => categories.id),
  basePrice: numeric('base_price', { precision: 10, scale: 2 }).notNull(),
  pixPrice: numeric('pix_price', { precision: 10, scale: 2 }),
  salePrice: numeric('sale_price', { precision: 10, scale: 2 }),
  stock: integer('stock').default(0),
  active: boolean('active').default(true),
  featured: boolean('featured').default(false),
  isNew: boolean('is_new').default(false),
  isBestseller: boolean('is_bestseller').default(false),
  images: jsonb('images').$type<string[]>().default([]),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
  metaTitle: text('meta_title'),
  metaDescription: text('meta_description'),
  viewCount: integer('view_count').notNull().default(0),
  weightKg: numeric('weight_kg', { precision: 6, scale: 3 }).default('0.3'),
  pkgHeightCm: numeric('pkg_height_cm', { precision: 6, scale: 2 }).default('5'),
  pkgWidthCm: numeric('pkg_width_cm', { precision: 6, scale: 2 }).default('15'),
  pkgLengthCm: numeric('pkg_length_cm', { precision: 6, scale: 2 }).default('20'),
  colors: text('colors').array().default([]),
  sizes: text('sizes').array().default([]),
  sizeChart: jsonb('size_chart').$type<Record<string, unknown>>().default({}),
  blingId: bigint('bling_id', { mode: 'number' }),
  videoUrl: text('video_url'),
  colorImages: jsonb('color_images').$type<Record<string, unknown>>().default({}),
});
